import { Toy } from './types';

export const TOYS: Toy[] = [
  {
    id: '1',
    name: 'Cosmic Explorer Robot',
    description: 'A friendly robot that teaches basic coding and space facts.',
    price: 49.99,
    category: 'educational',
    image: 'https://picsum.photos/seed/robot/400/400',
    rating: 4.8,
    color: 'bg-blue-400',
  },
  {
    id: '2',
    name: 'Rainbow Unicorn Plush',
    description: 'Soft, cuddly, and magical unicorn with a glowing horn.',
    price: 24.99,
    category: 'plush',
    image: 'https://picsum.photos/seed/unicorn/400/400',
    rating: 4.9,
    color: 'bg-pink-400',
  },
  {
    id: '3',
    name: 'Dino-Strike T-Rex',
    description: 'Roaring action figure with movable limbs and realistic sounds.',
    price: 34.99,
    category: 'action',
    image: 'https://picsum.photos/seed/dino/400/400',
    rating: 4.7,
    color: 'bg-green-400',
  },
  {
    id: '4',
    name: 'Master Builder Set',
    description: '500-piece creative building blocks for endless imagination.',
    price: 39.99,
    category: 'creative',
    image: 'https://picsum.photos/seed/blocks/400/400',
    rating: 4.6,
    color: 'bg-yellow-400',
  },
  {
    id: '5',
    name: 'Super Speed Racer',
    description: 'Remote-controlled car that can reach speeds of 15mph.',
    price: 59.99,
    category: 'action',
    image: 'https://picsum.photos/seed/car/400/400',
    rating: 4.5,
    color: 'bg-red-400',
  },
  {
    id: '6',
    name: 'Artistic Wonders Kit',
    description: 'Complete painting and drawing set for young artists.',
    price: 29.99,
    category: 'creative',
    image: 'https://picsum.photos/seed/art/400/400',
    rating: 4.8,
    color: 'bg-purple-400',
  },
];
